### ISSUE TITLE
Bug with never resuming charging

### ISSUE THREAD

**Issue by 0xCA** [Magisk-Modules-Repo/MC-s-Charging-Controller#1]
## Expected behaviour
You can plug out your phone at any time and after that plug it in back and charge.
## Actual behaviour
Sometimes when you unplug your phone and use it for some time and then plug it again it's not charging. It shows charging by led/icon/text at settings/etc and at "--info" it's stated as "Charging" but it's not. It's discharging.
## Steps to reproduce
Set Disable% and Enable%, for example at 80% and 70%. Wait until it hit 80% and show that it's not charging. Unplug your phone and use it. Occasionally realize that it's 25% and it's time to charge, plug in. See that it's indicating charging. Continue to use it and see 24%, 23%, 22, 21 and shut.
### Notes
After reboot it's charging again as usual. Also if you unplug it before it's charged to 80% nothing bad happens. You can charge it any time later as usual. The problem is only when it's hit the Disable%.
Some versions before it was possible to fix this by "--enable 70%" and re-plug the charger. It was charging. Now it's not working.
One more fact: when this problem takes place you can't "--reconf". It just saying that device is not charging.
### Tested at:
**Xiaomi Mi A1**, stock kernel, Android 8.0, latest stable Magisk.
**HTC One M9**, stock kernel, Android 7.0, latest stable Magisk.

**Comment by sjayminsgithub** [comment]
Can you do some testing for me ??? And also, if you could stay in contact at XDA via it would be a bit easier....
