### ISSUE TITLE
Oneplus 5t Oreo beta 3 installation fails

### ISSUE THREAD

**Issue by jperezdavinchi** [Magisk-Modules-Repo/MC-s-Charging-Controller#2]
First of all, thanks for your hard work.
I want to migrate from Magic Charging Switch to your module, I'm trying to install it (the device is charging during the installation), I can see how the charging is disabled and enabled in the compatibility test but the process fails with a message that says that my device is not compatible.

The Magic Charging Switch works properly and in the compatibility test the charging is disabled an re-enabled, could be a problem with the Magisk version?

Magisk manager is the 5.6.1(105) and Magisk is 16.0,
I also have BusyBox Magisk module 1.28.1.

The log sais something about "Permission denied".
[Here is the log of the installation](https://drive.google.com/file/d/1NAwpGHnFtqwFKaNF00v12cNlGTD5MoBL/view?usp=sharing)

Thank you again

**Comment by sjayminsgithub** [comment]
Hi, can you try the latest one from Magisk Manager and see if that works, it has some improvements in the compatibility test

**Comment by jperezdavinchi** [comment]
Hi, thanks for your response, I've updated magisk manager and the module has been installated successfully.
Thank you!

**Comment by sjayminsgithub** [comment]
The issue has been closed
