### ISSUE TITLE
uevent Sony Xperia XZs

### ISSUE THREAD

**Issue by daandav** [Magisk-Modules-Repo/MC-s-Charging-Controller#6]
If I understand your code correctly:

when configuring the references it searches for uevents containing "batt", "Batt", "Charging", "charging". However I think sony uses an event called "qpnp_smbcharger". So maybe an idea to add a search for "Charger", "charger"?

I will gladly help if you need any data from me (Xperia phone).

**Comment by sjayminsgithub** [comment]
Hi,
I can't understand what you mean by event, did you mean an event sent by the kernel, or the name of the uevent file ?? If it was the second one, there is no need for it, but if the first one, can you send me a sample of the uevent and details of the file ( PATH, MODE, etc... )

**Comment by sjayminsgithub** [comment]
Hi, are you there ?? If so, please reopen the issue. If you're having difficulty please ask here and I'd love the opportunity to assist you. Thanks.....

**Comment by pat357** [comment]
How can I reopen this issue ?

**Comment by pat357** [comment]
You asked daandav  for some additional things (sample of the uevent and details of the file ( PATH, MODE, etc... ), but I never saw this info.

**Comment by sjayminsgithub** [comment]
I didn't ask you to reopen, I asked daandav for this. Maybe a misunderstanding. Yep, he actually never provided that info so I closed the issue, and told him to feel free to reopen it whenever he's gotten them
